# Generated by Django 4.0.6 on 2022-08-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('土木工学科', '土木工学科'), ('建築学科', '建築学科'), ('電気電子工学科', '電気電子工学科'), ('機械工学科', '機械工学科'), ('生命応用科学科', '生命応用科学科'), ('情報工学科', '情報工学科'), ('秘密', '秘密')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.IntegerField(choices=[(1, '1回生'), (2, '2回生'), (3, '3回生'), (4, '4回生'), (5, 'それ以外'), (6, '秘密')]),
        ),
    ]
